name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up K3S
      uses: debianmaster/actions-k3s@v1.0.5
      id: k3s
      with:
        version: v1.21.2-k3s1

    - uses: evantorrie/mott-the-tidier@v1-beta
      with:
        gomods: |
          **/go.mod
          -tools/go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -v ./...

    - name: E2E Test
      run: go test -tags=integration -v ./test/e2e/...
