name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GO: 1.18

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO }}
      - uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
            -tools/go.mod
      - name: Build
        run: go build -v ./...

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO }}
      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO }}
      - name: Set up K3S
        uses: debianmaster/actions-k3s@v1.0.5
        id: k3s
        with:
          version: v1.21.2-k3s1
      - name: E2E Test
        run: go test -tags=integration -v ./test/e2e/...
